version: "3.1"

services:
  postgres:
    image: postgres:14.1
    container_name: invoices-db-container
    environment:
      POSTGRES_DB: invoices
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    user: postgres
    ports:
      - "5442:5432"